# Eat Safe, Love

## Notebook Set Up

In [1]:
# Import dependencies
from pymongo import MongoClient
import pandas as pd
from pprint import pprint
import matplotlib.pyplot as plt

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# Confirm that our new database was created
print(mongo.list_database_names())

['admin', 'autosaurus', 'config', 'local', 'uk_food']

In [4]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [5]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [6]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [7]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene': 20}

# Use count_documents to display the number of documents in the result
establishments.count_documents(query)

# Display the first document in the results using pprint
pprint(establishments.find_one(query))

{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': '0',
 'RatingValueInt': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('65e294bbddfff6bf5ca22bb2'),
 'geocode': {'latitude': Decimal128('50.769705'),
             'longitude': Decimal128('0.27694')},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [8]:
# Convert the result to a Pandas DataFrame
hygiene = establishments.find_one(query)
list_hygiene = list(hygiene)

hygiene_df = pd.DataFrame(list_hygiene)
print(len(hygiene_df))

# Display the number of rows in the DataFrame
# print(hygiene_df.shape[0])

# Display the first 10 rows of the DataFrame
# hygiene_df.head(10)

hygiene_df.head(10)

29

                          0
0                       _id
1                    FHRSID
2         ChangesByServerID
3  LocalAuthorityBusinessID
4              BusinessName
5              BusinessType
6            BusinessTypeID
7              AddressLine1
8              AddressLine2
9              AddressLine3

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [9]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {'LocalAuthorityName':{'$regex':'London'},'RatingValue':{'$gte':'4'}}

# Use count_documents to display the number of documents in the result
print(establishments.count_documents(query))
                               
# Display the first document in the results using pprint
pprint(establishments.find_one(query))

66
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': '4',
 'RatingValueInt': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('65e294bbddfff6bf5ca245d5'),
 'geocode': {'latitude': Decimal128('51.369321'),
             'longitude': Decimal128('0.508551')},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [10]:
# Convert the result to a Pandas DataFrame
london = (establishments.find(query))
london_df = pd.DataFrame(london)

# Display the number of rows in the DataFrame
print(len(london_df))
# Display the first 10 rows of the DataFrame
london_df.head(10)

66

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,RatingValueInt
0,65e294bbddfff6bf5ca245d5,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 5, 'Structural': 10, 'ConfidenceIn...",FHRS,"{'longitude': 0.508551, 'latitude': 51.369321}",,4627.439468,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",4
1,65e294bbddfff6bf5ca248f9,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.249255999922752, 'latitude': 5...",,4627.873179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",5
2,65e294bbddfff6bf5ca2543d,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.561954, 'latitude': 51.543831}",,4631.968418,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",4
3,65e294bbddfff6bf5ca2623f,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.346336990594864, 'latitude': 5...",,4636.846754,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",5
4,65e294bbddfff6bf5ca26240,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.346325, 'latitude': 51.464078}",,4636.847650,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",5
5,65e294bbddfff6bf5ca26946,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.287555, 'latitude': 51.504071}",,4640.460834,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",5
6,65e294bcddfff6bf5ca28a50,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.069286, 'latitude': 51.501121}",,4648.301822,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",5
7,65e294bcddfff6bf5ca28e1a,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.048006, 'latitude': 51.503733}",,4649.173485,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",4
8,65e294bcddfff6bf5ca28e35,294606,0,PI/000016185,WH Smith,Retailers - other,4613,London City Airport,Silvertown London,,...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.0479655750095844, 'latitude': ...",,4649.188850,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",5
9,65e294bcddfff6bf5ca28e38,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.047966, 'latitude': 51.504112}",,4649.188826,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",5

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [15]:
# Check that the new restaurant was inserted
print(establishments.find_one({"BusinessName":"Howe and Co Fish and Chips - Van 17"}))

{'_id': ObjectId('65e294bcddfff6bf5ca28401'), 'FHRSID': 1380578, 'ChangesByServerID': 0, 'LocalAuthorityBusinessID': '14425', 'BusinessName': 'Howe and Co Fish and Chips - Van 17', 'BusinessType': 'Mobile caterer', 'BusinessTypeID': 7846, 'AddressLine1': 'Restaurant And Premises 107A Plumstead High Street', 'AddressLine2': '', 'AddressLine3': 'Plumstead', 'AddressLine4': 'Greenwich', 'PostCode': 'SE18 1SE', 'Phone': '', 'RatingValue': '5', 'RatingKey': 'fhrs_5_en-gb', 'RatingDate': '2021-11-11T00:00:00', 'LocalAuthorityCode': '511', 'LocalAuthorityName': 'Greenwich', 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk', 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk', 'scores': {'Hygiene': 0, 'Structural': 0, 'ConfidenceInManagement': 0}, 'SchemeType': 'FHRS', 'geocode': {'longitude': Decimal128('0.0925370007753372'), 'latitude': Decimal128('51.4875335693359')}, 'RightToReply': '', 'Distance': 4646.95593107927, 'NewRatingPending': False, 'meta': {'dataSource': None, 'extractDate': '0001-01-01T00:00:00', 'itemCount': 0, 'returncode': None, 'totalCount': 0, 'totalPages': 0, 'pageSize': 0, 'pageNumber': 0}, 'links': [{'rel': 'self', 'href': 'http://api.ratings.food.gov.uk/establishments/1380578'}], 'RatingValueInt': 5}

In [11]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.490142
longitude = 0.08384

query = {'geocode.latitude':{'$gte':latitude-degree_search,'$lte':latitude+degree_search},
        'geocode.longitude':{'$gte':longitude-degree_search,'$lte':longitude+degree_search},
         'RatingValue':5}
sort = [('scores.Hygiene', 1)]
limit = 5

query_results=list(establishments.find(query).sort(sort).limit(limit))
print(len(query_results))
pprint(query_results)

# Print the results
# pprint(list(establishments.find(query).sort(sort).limit(limit)))

0
[]

In [12]:
# Convert result to Pandas DataFrame
establishments_1 = list(establishments.find(query).sort(sort).limit(limit))
df_1 = pd.DataFrame(establishments_1)
print(df_1)

Empty DataFrame
Columns: []
Index: []

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [13]:
# Create a pipeline that:
# 1. Matches establishments with a hygiene score of 0
bad_hygiene = {'$match': {'scores.Hygiene':0}}
# 2. Groups the matches by Local Authority
group_query = {'$group': {'_id': {"LocalAuthorityName": "$LocalAuthorityName",
                                 'count': {'$sum': 1 }
                                 }
                         }}
# 3. Sorts the matches from highest to lowest
sort_values = {'$sort': {'count': +1 }}
# Print the number of documents in the result
pipeline = [bad_hygiene,group_query, sort_values]
# Print the first 10 results
results = list(establishments.aggregate(pipeline))

pprint(results[0:10])

[{'_id': {'LocalAuthorityName': 'Braintree', 'count': 1}},
 {'_id': {'LocalAuthorityName': 'Kensington and Chelsea', 'count': 1}},
 {'_id': {'LocalAuthorityName': 'Wealden', 'count': 1}},
 {'_id': {'LocalAuthorityName': 'Epping Forest', 'count': 1}},
 {'_id': {'LocalAuthorityName': 'Waltham Forest', 'count': 1}},
 {'_id': {'LocalAuthorityName': 'Mid Sussex', 'count': 1}},
 {'_id': {'LocalAuthorityName': 'Tower Hamlets', 'count': 1}},
 {'_id': {'LocalAuthorityName': 'Lewisham', 'count': 1}},
 {'_id': {'LocalAuthorityName': 'Canterbury City', 'count': 1}},
 {'_id': {'LocalAuthorityName': 'Dartford', 'count': 1}}]

In [14]:
# Convert the result to a Pandas DataFrame
bad_hygiene_df = pd.json_normalize(results)
# Display the number of rows in the DataFrame
print("Total rows in bad hygiene_df is",len(bad_hygiene_df))
# Display the first 10 rows of the DataFrame
bad_hygiene_df.head(10)

Total rows in bad hygiene_df is 55

   _id.LocalAuthorityName  _id.count
0               Braintree          1
1  Kensington and Chelsea          1
2                 Wealden          1
3           Epping Forest          1
4          Waltham Forest          1
5              Mid Sussex          1
6           Tower Hamlets          1
7                Lewisham          1
8         Canterbury City          1
9                Dartford          1